"""remove test column

Revision ID: 5d87e93976d0
Revises: b3eca77e467e
Create Date: 2022-04-23 00:28:45.845525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d87e93976d0'
down_revision = 'b3eca77e467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
